/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IntegerConv.h"


void
intconv_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  tohex_1_arg;
	int  *result_2;
	int  tooct_1_arg;
	int inputValue;
#ifndef	DEBUG
	clnt = clnt_create (host, INTCONV, INTCONV_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	printf("Enter the integer value: ");
	scanf("%d",&inputValue);
	tohex_1_arg = inputValue;
	result_1 = tohex_1(&tohex_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("\nInteger->Hex: %x\n",*result_1);
	tooct_1_arg = inputValue;
	result_2 = tooct_1(&tooct_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Integer->Oct: %o\n",*result_2);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	intconv_1 (host);
exit (0);
}
