/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IntegerConv.h"

int *
tohex_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("\nRecieved %d from client\n", *argp);
	result = *argp;
	printf("%d -> %x\n",*argp,result);
	return &result;
}

int *
tooct_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	printf("Recieved %d from client\n", *argp);
	result = *argp;
	printf("%d -> %o\n",*argp,result);
	return &result;
}
