/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "intToHex.h"


void
inttohex_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  tohex_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, INTTOHEX, INTTOHEX_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	puts("Enter a number: ");
	scanf("%d" , &tohex_1_arg);
	result_1 = tohex_1(&tohex_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Hex: %x \n",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	inttohex_1 (host);
exit (0);
}
